config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/messages', to: 'message_threads#index', as: :message_threads
  post '/messages', to: 'message_threads#create'
  get '/messages/:uuid', to: 'message_threads#show', as: :message_thread
  post '/messages/:uuid/messages', to: 'messages#create', as: :message_thread_messages
  delete '/messages/:uuid', to: 'message_threads#destroy'

  get '/settings', to: 'settings#index'

  resources :ads do
    member do
      resources :message_threads, as: :ad_messages, only: [:new]
    end
  end
  resources :peers
  get '/marketplace', to: "marketplace#index"

  namespace :api do
    namespace :v1 do
      resources :ads, only: [:index, :create, :destroy]
      resources :messages, only: [:create]
      post 'webhook', to: 'webhook#create'
      get 'webhook/:uuid/:token', to: 'webhook#show'
      get 'status', to: 'status#show'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["WEB_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["WEB_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'peers#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
  include HasUuid

  paginates_per 10

  belongs_to :peer, optional: true # set if the ad comes from a peer
  has_many :message_threads, dependent: :destroy
  has_many :webhook_sends, as: :resource, class_name: 'Webhook::Send', dependent: :destroy
  has_many :webhook_receipts, as: :resource, class_name: 'Webhook::Receipt', dependent: :destroy

  enum :messaging_type, {
    direct: 0,
    blinded: 1
  }

  enum :trust_channel, {
    low_trust: 1, 
    high_trust: 3,
  }

  after_commit :propagate_to_peers
  after_save :log_receipt, if: :peer
  before_create :set_defaults

  delegate :name, to: :peer, prefix: true, allow_nil: true

  before_validation :initialize_keys, if: :blinded?
  validates_presence_of :public_key, if: :blinded?
  validates_presence_of :secret_key, if: -> { blinded? && self_authored? }

  before_validation :initialize_onion_address, if: :direct?
  validates :onion_address, presence: true, if: :direct?

  validates :description, :title, :messaging_type, presence: true

  scope :self_authored, -> { where(peer_id: nil) }
  scope :from_peers, -> { where.not(peer_id: nil) }

  scope :to_sync_to, -> (peer) {
    if peer.low_trust?
      where(trust_channel: :trust_level)
    else
      self
    end
  }

  def set_defaults
    self.trust_channel ||= :low_trust
  end

  def log_receipt
    Webhook::Receipt.create!(resource: self, uuid: uuid, peer: peer, action: 'upsert')
  end

  def initialize_keys
    # secret key is set if I own this ad.
    # only public key is set if this came from someone else
    return if secret_key.present? || public_key.present?

    skey = RbNaCl::PrivateKey.generate
    pkey = skey.public_key


    self[:secret_key] = skey.to_bytes
    self[:public_key] = pkey.to_bytes
  end

  def base64_public_key
    return nil if public_key.blank?

    Base64.encode64(public_key)
  end

  def base64_public_key=(key)
    return if key.blank?

    self.public_key = Base64.decode64(key)
  end

  def initialize_onion_address
    self.onion_address ||= configatron.my_onion
  end

  def propagate_to_peers
    peers_in_trust_level.with_public_key_resolved.where.not(id: peer_id).find_each do |peer|
      Webhook::ResourceSendJob.perform_later(
        self.class.name,
        id,
        uuid,
        peer,
        deleted: transaction_include_any_action?([:destroy])
      )
    end
  end

  def peers_in_trust_level
    Peer.where(trust_level: [:high_trust, trust_channel].uniq)
  end

  # ResourceSendJob#from_name_for_resource API
  def ad
    self
  end

  def self_authored?
    peer_id.nil?
  end

  # sanitize json version of secret key globally
  def serializable_hash(*args)
    if blinded?
      super(except: [:id, :peer_id, :onion_address, :secret_key, :public_key], methods: [:base64_public_key])
    else
      super(except: [:id, :peer_id, :secret_key, :public_key])
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[show edit update destroy]

  # GET /ads or /ads.json
  def index
    @ads = Ad.includes(:peer).where(peer: nil)
  end

  # GET /ads/1 or /ads/1.json
  def show; end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit; end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ad
    @ad = Ad.find_by(uuid: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ad_params
    params.require(:ad).permit(:title, :description, :messaging_type, :trust_channel)
  end
end

app/controllers/api/v1/ads_controller.rb
class Api::V1::AdsController < Api::V1::BaseController
  skip_before_action :verify_peer_ownership, only: [:index]

  def index
    results = Ad.to_sync_to(peer).order(:created_at).page(params[:page]).per(500)
    render json: {
      total_pages: results.total_pages,
      last_page: results.last_page?,
      results: results
    }
  end

  def create
    ad = peer.ads.find_or_initialize_by(uuid: params[:uuid])

    perform = if params[:action_taken] == 'delete' # couldn't get _method delete to route, screw it
      -> { ad.destroy if ad.persisted? } # it may have been deleted by another peer
    else
      -> { ad.update ad_params.merge(hops: ad_params[:hops] + 1) }
    end
    
    if perform.call
      head :ok
    else
      render json: {
        errors: ad.errors
      }, status: :unprocessable_entity
    end
  end

  private

  def ad_params
    if params[:action_taken] == 'upsert'
      params.require(:ad).permit(
        :title,
        :uuid,
        :description,
        :hops,
        :messaging_type,
        :trust_channel,
        :base64_public_key,
        :onion_address,
        :created_at,
        :updated_at
      )
    else
      params
    end
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  def ad_trust_channel_description(name)
    case name
    when "high_trust"
      %Q{
        Only your high trust peers will share this with their high trust peers.
      }
    when "low_trust"
      %Q{
        All of your peers will share this with all of their peers.
      }
    end
  end

  def ad_trust_channel_icon(name)
    case name
    when "high_trust"
      icon_shield_check
    when "low_trust"
      icon_shield_exclamation
    end
  end

end

app/helpers/api/v1/ads_helper.rb
module Api::V1::AdsHelper
end

app/views/ads/_ad.html.erb
<div class="paper__title">
  <%= ad.title %>
</div>
<div class="mt-5 border-t border-gray-200">
  <dl class="sm:divide-y sm:divide-gray-200">
    <div class="<%= controller_name == "messages" ? 'hidden' : '' %>">
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
        <dt class="text-sm font-medium text-gray-500 flex">
          Description

          <div class="grow ml-2" data-tooltip="Do not visit any URLs from a peer. They may try to track your IP or worse.">
            <%= icon_question %>
          </div>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= ad.description %>
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4"  data-tooltip="Coming soon...">
        <dt class="text-sm font-medium text-gray-500">
          Price
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          $$$
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
        <dt class="text-sm font-medium text-gray-500">
          Messaging type
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center gap-2">
          <%= messaging_type_icon(ad.messaging_type.to_s) %>
          <%= ad.messaging_type.humanize %>
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
      <dt class="text-sm font-medium text-gray-500">
        Trust channel
      </dt>
      <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center gap-2">
        <%= ad_trust_channel_icon(ad.trust_channel.to_s) %>
        <%= ad.trust_channel.humanize %>
      </dd>
    </div>

      <% if ad.peer %>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
          <dt class="text-sm font-medium text-gray-500">
            Through
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
            <%= link_to ad.peer_name, peer_path(ad.peer) %>
          </dd>
        </div>
      <% end %>
    </div>
  </dl>
</div>

<% unless controller_name == 'messages' %>
  <div class="w-full flex items-center mt-4">
    <% if ad.peer.blank? %>
      <%= link_to 'Edit this ad', edit_ad_path(ad), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Delete this ad', ad_path(ad), method: :delete, data: { confirm: "Are you sure you want to delete this ad?" }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium mr-2" %>
      </div>
    <% end %>
    <%= link_to "Back to #{ad.peer.present? ? 'Marketplace' : 'Ads'}", ad.peer.present? ? marketplace_path : ads_path, class: "inline-flex items-center px-6 py-3 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    <% if ad.peer.present? %>
      <%= link_to 'Message', new_ad_message_path(ad), class: "ml-4 inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    <% end %>
  </div>
<% end %>

app/views/ads/_form.html.erb
<%= form_with(model: ad, class: "contents") do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation" class="bg-rose-50 text-rose-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :messaging_type, class: "mb-2" %>
    <div class="mt-5 grid gap-4 grid-cols-2">
      <%= form.collection_radio_buttons :messaging_type, Ad.messaging_types, :first, :first, html_options: { class: 'mt-2' } do |b| %>
        <%= b.label class: "border border-2 border-dashed p-4" do %>
          <div class="relative flex items-start">
            <div class="flex items-center h-5">
              <%= b.radio_button html_options: { class: "focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300" } %>
            </div>
            <div class="ml-3 text-sm">
              <div class="flex mb-4">
                <label for="small" class="font-medium text-gray-700 mr-2"><%= b.text.humanize %></label>
                <%= messaging_type_icon(b.text) %>
              </div>

              <p id="small-description" class="text-gray-500"><%= messaging_type_description(b.text) %></p>
            </div>
          </div>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="my-5">
  <%= form.label :trust_channel, class: "mb-2" %>
    <div class="mt-5 grid gap-4 grid-cols-2">
      <%= form.collection_radio_buttons :trust_channel, Ad.trust_channels, :first, :first, html_options: { class: 'mt-2' } do |b| %>
        <%= b.label class: "border border-2 border-dashed p-4" do %>
          <div class="relative flex items-start">
            <div class="flex items-center h-5">
              <%= b.radio_button html_options: { class: "focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300" } %>
            </div>
            <div class="ml-3 text-sm">
              <div class="flex mb-4">
                <label for="small" class="font-medium text-gray-700 mr-2"><%= b.text.humanize %></label>
                <%= ad_trust_channel_icon(b.text) %>
              </div>
              <p id="small-description" class="text-gray-500"><%= ad_trust_channel_description(b.text) %></p>
            </div>
          </div>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<div class="paper">
  <h1 class="paper__title">Editing ad</h1>

  <%= render "form", ad: @ad %>

  <%= link_to "Show this ad", @ad, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ads", ads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ads/index.html.erb
<% content_for :page_title, 'Your ads' %>



<% if @ads.empty? %>
  <%= empty_state_container do %>

    <h2 class="text-4xl">
      You have no ads.
    </h2>

    <h3 class="text-lg mt-4">
      Create an ad to broadcast what you offer to your peers.
    </h3>

    <svg xmlns="http://www.w3.org/2000/svg" class="h-44 w-44" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
    </svg>

    <%= link_to new_ad_path, class: "btn relative inline-flex items-center justify-center my-2 mx-4 rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:bg-blue-500" do %>
      <%= icon_plus %>
      New ad
    <% end %>

  <% end %>

<% else %>

  <div class="p-4 w-full">
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Your ads</h1>
      <%= link_to 'New ad', new_ad_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>


    <!-- Peer list (smallest breakpoint only) -->
    <div class="shadow md:hidden">
      <ul role="list" class="mt-2 divide-y divide-gray-200 overflow-hidden shadow md:hidden">
        <% @ads.find_each do |ad| %>
          <li>
            <%= link_to ad, class: "block px-4 py-4 bg-white hover:bg-gray-50" do %>
              <span class="flex items-center space-x-4">
                <span class="flex-1 flex space-x-2 truncate">
                  <!-- Heroicon name: solid/cash -->
                  <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                  </svg>
                  <span class="flex flex-col text-gray-500 text-sm truncate">
                    <span class="truncate"><%= ad.title %></span>
                    <span class="text-gray-900 font-medium text-xs"><%= ad.hops %></span>
                    <time datetime="2020-07-11">July 11, 2020</time>
                  </span>
                </span>
                <!-- Heroicon name: solid/chevron-right -->
                <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul>

      <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200" aria-label="Pagination">
        <div class="flex-1 flex justify-between">
          <a href="#" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:text-gray-500">
            Previous
          </a>
          <a href="#" class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:text-gray-500">
            Next
          </a>
        </div>
      </nav>
    </div>

    <!-- Large viewport table -->
    <div class="flex flex-col hidden md:block">
      <div class="">
        <div class="py-2 align-middle inline-block min-w-full">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Title
                  </th>
                  
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Responses
                  </th>
        
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">View</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                <%= @ads.find_each.with_index do |ad, index| %>
                  <% even = index % 2 %>
                  <tr class="<%= even ? 'bg-white' : 'bg-gray-50'%>">
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">                
                      <%= link_to ad.title, ad_path(ad) %>
                    </td>
          
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">                
                      <%= link_to pluralize(ad.message_threads.size, "response"), messages_path() %>
                    </td>

                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <%= link_to 'Edit', edit_ad_path(ad), class: "text-blue-600 hover:text-blue-900" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/ads/new.html.erb
<div class="paper">
  <h1 class="paper__title">New ad</h1>

  <%= render "form", ad: @ad %>

  <%= link_to 'Back to ads', ads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ads/show.html.erb
<div class="paper">
  <%= render @ad %>
</div>