config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/messages', to: 'message_threads#index', as: :message_threads
  post '/messages', to: 'message_threads#create'
  get '/messages/:uuid', to: 'message_threads#show', as: :message_thread
  post '/messages/:uuid/messages', to: 'messages#create', as: :message_thread_messages
  delete '/messages/:uuid', to: 'message_threads#destroy'

  get '/settings', to: 'settings#index'

  resources :ads do
    member do
      resources :message_threads, as: :ad_messages, only: [:new]
    end
  end
  resources :peers
  get '/marketplace', to: "marketplace#index"

  namespace :api do
    namespace :v1 do
      resources :ads, only: [:index, :create, :destroy]
      resources :messages, only: [:create]
      post 'webhook', to: 'webhook#create'
      get 'webhook/:uuid/:token', to: 'webhook#show'
      get 'status', to: 'status#show'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["WEB_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["WEB_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'peers#index'
end

app/models/message_thread.rb
class MessageThread < ApplicationRecord
  include HasUuid

  belongs_to :ad, optional: true
  belongs_to :peer # is always pointing toward lead - null if user is lead, terminal state

  has_many :messages, dependent: :destroy

  delegate :blinded?, :direct?, :high_trust?, :low_trust?, to: :ad

  attr_accessor :body, :from_peer

  validates_presence_of :body, unless: :from_peer

  enum :claim, {
    intermediate: 0,
    mine: 1,
  }

  # called for Blinded threads
  def initialize_keys!
    return if secret_key.present? || public_key.present?

    skey = RbNaCl::PrivateKey.generate
    pkey = skey.public_key

    self.secret_key = skey.to_bytes
    self.public_key = pkey.to_bytes
  end

  def base64_public_key
    return nil if public_key.blank?

    Base64.encode64(public_key)
  end

  # called for Direct threads lead-side
  def initialize_peer!
    self.peer = Peer.find_or_initialize_by(onion_address: ad.self_authored? ? peer.onion_address : ad.onion_address)
    self.peer.name ||= ordinalized_peer_name
    self.peer.save!
  end

  def lead_view?
    secret_key.present?
  end

  def ordinalized_peer_name
    return "#{peer.name} via Direct Message" if direct?

    peer_name, distance = if lead_view?
      [ad.peer_name, ad.hops]
    else # advertiser's pov
      [peer.name, hops]
    end

    # is an immediate peer, just show their name
    return peer_name if (hops || ad.hops) == 1

    "#{distance.ordinalize}˚ peer via #{peer_name}"
  end

  def multi_hop?
    hops.blank? || hops > 1
  end
end

app/controllers/message_threads_controller.rb
class MessageThreadsController < ApplicationController
  before_action :set_message_thread, only: %i[ show update destroy ]

 # GET /message_threads or /message_threads.json
 def index
  @threads = MessageThread
    .mine
    .includes(:ad, :peer, :messages)
    .order(updated_at: :desc).all
end

# GET /message_threads/1 or /message_threads/1.json
def show
  @threads = MessageThread
    .mine
    .includes(:ad, :peer, :messages)
    .order(updated_at: :desc)
    .all
  @thread = @message_thread
end

# GET /message_threads/new or /ads/:id/message_threads/new
def new
  ad = Ad.where(uuid: params[:id]).first
  @message_thread = MessageThread.new(ad: ad, peer: ad.peer)
end

# POST /message_threads or /message_threads.json
def create
  @message_thread = MessageThread.new(message_thread_params.merge(claim: :mine))
  @message_thread.initialize_keys! if @message_thread.blinded?
  @message_thread.initialize_peer! if @message_thread.direct?

  respond_to do |format|
    if @message_thread.save
      message = @message_thread.messages.build(body: @message_thread.body, author: :lead)
      if @message_thread.blinded?
        message.type = 'Messages::LeadMessage'
        message = message.becomes(Messages::LeadMessage)
        message.encrypt_body!
      else
        message.type = 'Messages::DirectMessage'
        message = message.becomes(Messages::DirectMessage)
      end
      message.save!
      format.html { redirect_to message_thread_url(@message_thread) }
      format.json { render :show, status: :created, location: @message_thread }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @message_thread.errors, status: :unprocessable_entity }
    end
  end
end


# DELETE /message_threads/1 or /message_threads/1.json
def destroy
  @message_thread ||= MessageThread.find(params[:id])
  @message_thread.destroy

  respond_to do |format|
    format.html { redirect_to message_threads_url }
    format.json { head :no_content }
  end
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_message_thread
    @message_thread = MessageThread.find_by(uuid: params[:uuid])
  end

  # Only allow a list of trusted parameters through.
  def message_thread_params
    params.require(:message_thread).permit(:ad_id, :peer_id, :body)
  end
end

app/views/message_threads/_form.html.erb
<%= form_with(model: message_thread, class: "contents") do |form| %>
  <% if message_thread.errors.any? %>
    <div id="error_explanation" class="bg-rose-50 text-rose-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(message_thread.errors.count, "error") %> prohibited this message_thread from being saved:</h2>

      <ul>
        <% message_thread.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @message_thread.ad.present? %>
    <div class="my-5">
      <%= form.hidden_field :ad_id %>
      <%= form.hidden_field :peer_id %>
      <%= label_tag 'To' %>

      <div class="flex items-center">
        <%= icon_right_arrow_small %>

        <%= message_thread.ad.peer_name %>
        <% if message_thread.ad.hops > 1 %>
          <div class="flex items-center" data-tooltip="This came through <%= message_thread.ad.peer_name %>">
            <%= icon_right_arrow_small %>
            <%= pluralize message_thread.ad.hops, 'peer' %> away
          </div>
        <% end %>
        <span data-tooltip="<%= message_thread.high_trust? ? 'Found through high trust peers.' : 'Found through low trust peers.' %>">
          <%= ad_trust_channel_icon(message_thread.ad.trust_channel) %>
        </span>

        <span data-tooltip="<%= message_thread.blinded? ? 'Your .onion will not be disclosed.' : 'Your .onion will be disclosed.' %>">
          <%= messaging_type_icon(message_thread.ad.messaging_type) %>
        </span>
      </div>
    </div>
    <div class="my-5">
      <%= form.hidden_field :ad_id %>
      <%= label_tag 'Subject' %>

      <%= text_field_tag :subject, "Re: #{@message_thread.ad.title}" ,class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full opacity-70", disabled: true %>

    </div>
  <% else %>
    <div class="my-5">
      <%= form.label :peer_id %>
      <%= form.text_field :peer_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit 'Send', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/message_threads/_message.html.erb
<div id="<%= dom_id message %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Ad:</strong>
    <%= message.ad_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Peer:</strong>
    <%= message.peer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= message.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this message", message, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this message', edit_message_path(message), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/message_threads/_messages.html.erb
<%= detail_sidebar do %>
  <% @threads.each do |thread| %>
    <%= link_to thread, class: "DetailSidebar__item block px-4 py-6 border-b #{@thread == thread ? 'DetailSidebar__item--selected' : ''}", data: { "turbo-frame": "detail_view" , action: "detail-sidebar#choose"} do %>
      <span class="flex items-center space-x-4 w-full">
        <span class="flex-1 flex space-x-2 truncate">
      
          <span class="flex flex-col text-gray-500 text-ellipsis overflow-hidden">
            <span class="DetailSidebar__item__title truncate font-bold text-gray-800"><%= thread.ad.title %></span>
            
            <span class="DetailSidebar__item__subtitle text-gray-900 text-xs">
              <%= thread.ordinalized_peer_name %>
            </span>
          </span>
        </span>

        <div class="icon--trash" data-action="click->detail-sidebar#delete" data-detail-sidebar-endpoint-param="messages" data-detail-sidebar-record-id-param="<%= thread.uuid %>">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
          </svg>
        </div>
        
        <!-- Heroicon name: solid/chevron-right -->
        <div class='icon--chevron'>
          <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        </div>
      
      </span>
    <% end %>
  <% end %>
<% end %>

app/views/message_threads/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/message_threads/index.html.erb
<% if @threads.empty? %>

  <%= empty_state_container do %>
    <h2 class="text-4xl">
      You have no messages.
    </h2>

    <h3 class="text-lg mt-4">
      Get out there and make some noise.
    </h3>

    <%= icon_empty_inbox %>
  <% end %>

<% else %>
  <%= render partial: 'messages' %>

  <%= detail_sidebar_body %>
<% end %>

app/views/message_threads/new.html.erb
<div class="paper">
  <h1 class="paper__title">Respond to ad</h1>

  <%= render "form", message_thread: @message_thread %>

  <%= link_to 'Back to ad', ad_path(@message_thread.ad), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

app/views/message_threads/show.html.erb
<%= render partial: 'messages' %>

<turbo-frame id="detail_view" data-turbo-action="advance" class="DetailSidebar__body">
  <%= form_with(model: [@thread, @thread.messages.build], class: "rounded m-6 lg:m-8 pr-10 lg:pr-0 flex") do |form| %>
    <%= form.hidden_field :ad_id %>
    <%= form.hidden_field :peer_id %>
    <%= form.hidden_field :message_thread_id %>
    <%= form.text_area :body, rows: 2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 w-full" %>
    <%= form.submit 'Send', class: "rounded-lg ml-2 py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  <%end %>

  <!-- Thread section-->
  <ul role="list" class="py-4 space-y-2 sm:px-6 sm:space-y-4 lg:px-8">
    <% @thread.messages.order(created_at: :desc).each do |message| %>
      <li class="<%= message.lead? ? 'bg-blue-100 ml-32' : 'bg-white mr-32' %> px-4 py-6 shadow sm:rounded-lg sm:px-6">
        <div class="sm:flex sm:justify-between sm:items-baseline">
          <p class="mt-1 text-sm text-gray-600 whitespace-nowrap sm:mt-0">
            <time datetime="2021-01-28T19:24"><%= local_time_ago message.created_at %></time>
          </p>
        </div>
        <div class="mt-4 space-y-6 text-sm text-gray-800">
          <p><%= message.body %></p>
        </div>
      </li>
    <% end %>
  </ul>

</turbo-frame>