config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/messages', to: 'message_threads#index', as: :message_threads
  post '/messages', to: 'message_threads#create'
  get '/messages/:uuid', to: 'message_threads#show', as: :message_thread
  post '/messages/:uuid/messages', to: 'messages#create', as: :message_thread_messages
  delete '/messages/:uuid', to: 'message_threads#destroy'

  get '/settings', to: 'settings#index'

  resources :ads do
    member do
      resources :message_threads, as: :ad_messages, only: [:new]
    end
  end
  resources :peers
  get '/marketplace', to: "marketplace#index"

  namespace :api do
    namespace :v1 do
      resources :ads, only: [:index, :create, :destroy]
      resources :messages, only: [:create]
      post 'webhook', to: 'webhook#create'
      get 'webhook/:uuid/:token', to: 'webhook#show'
      get 'status', to: 'status#show'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["WEB_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["WEB_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'peers#index'
end

app/models/peer.rb
class Peer < ApplicationRecord
  has_many :ads, dependent: :destroy
  has_many :webhook_sends, dependent: :destroy, class_name: 'Webhook::Send'
  has_many :webhook_receipts, dependent: :destroy, class_name: 'Webhook::Receipt'
  has_many :message_threads, dependent: :destroy
  has_many :messages, dependent: :destroy

  enum :trust_level, {
    banned: 0, # ignore completely
    low_trust: 1,
    high_trust: 3,
  }

  before_create :set_defaults
  after_commit -> { Webhook::StatusCheckJob.perform_later(self) }, on: :create
  after_commit -> { PeerSyncAdsJob.perform_later(self ) }, on: [:create, :update], if: -> { saved_change_to_attribute?(:trust_level) }

  validates :onion_address, uniqueness: true, presence: true

  scope :with_public_key_resolved, -> { where.not(public_key: nil) }

  def set_defaults
    self.trust_level ||= :low_trust
  end

  def get_status
    PeaceNet.get(self, '/api/v1/status.json')
  end

  def incoming_ad_trust_channel_allowed?(channel)
    channel == 'low_trust' || channel == trust_level
  end
end

app/controllers/peers_controller.rb
class PeersController < ApplicationController
  before_action :set_peer, only: %i[show edit update destroy]

  # GET /peers or /peers.json
  def index
    @peers = Peer.order(trust_level: :desc).all
  end

  # GET /peers/1 or /peers/1.json
  def show; 
    @peers = Peer.all
  end

  # GET /peers/new
  def new
    @peer = Peer.new(trust_level: 'high_trust')
  end

  # GET /peers/1/edit
  def edit; end

  # POST /peers or /peers.json
  def create
    @peer = Peer.new(peer_params)

    respond_to do |format|
      if @peer.save
        format.html { redirect_to @peer, notice: 'Peer was successfully created.' }
        format.json { render :show, status: :created, location: @peer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peers/1 or /peers/1.json
  def update
    respond_to do |format|
      if @peer.update(peer_params)
        format.html { redirect_to @peer, notice: 'Peer was successfully updated.' }
        format.json { render :show, status: :ok, location: @peer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peers/1 or /peers/1.json
  def destroy
    @peer.destroy
    respond_to do |format|
      format.html { redirect_to peers_url, notice: 'Peer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_peer
    @peer = Peer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def peer_params
    params.require(:peer).permit(:name, :onion_address, :trust_level)
  end
end

app/helpers/peers_helper.rb
module PeersHelper
  def peer_online_status(peer, type: :large)
    if peer.last_online_at.nil?
      status = 'Unknown'
      color = 'yellow'
      circleColor = '#EF4444'
    elsif peer.last_online_at > 10.minutes.ago
      status = 'Online'
      color = 'green'
      circleColor = '#22C55E'
    else
      status = 'Offline'
      color = 'rose'
      circleColor = '#DC2626'
    end

    if type == :large
      tag.span(
        class: "inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium bg-#{color}-100 text-#{color}-800",
        "data-tooltip": "Last seen:  #{status == 'Unknown' ? 'Never' : time_ago_in_words(peer.last_online_at) + ' ago'}",
        'aria-label': "Connection status for #{peer.name}"
      ) do
        concat(tag.svg(class: "-ml-0.5 mr-1.5 h-2 w-2 text-#{color}-400", fill: 'currentColor', viewBox: '0 0 8 8') do
          tag.circle cx: '4', cy: '4', r: '3'
        end)
        concat status
      end
    else
      tag.svg(class: " mr-1 h-2 w-2", fill: circleColor, viewBox: '0 0 8 8') do
        tag.circle cx: '4', cy: '4', r: '3'
      end
    end
  end

  def peer_ads_in(timeframe: 30.days.ago..Time.current)
    @peer.ads.where(created_at: timeframe).count
  end

  def peer_onion_short(peer)
    "#{peer.onion_address[..5]}...#{peer.onion_address[-13..]}"
  end

  def peer_trust_levels
    if action_name == 'edit'
      Peer.trust_levels.to_a.reverse  
    else
      Peer.trust_levels.to_a.reject {|name, value| name === 'banned' }.reverse
    end
  end

  def peer_trust_level_description(name)
    case name
    when "high_trust"
      "Tell your peers you really trust ads from this person."
    when "low_trust"
      "Tell your peers to you do not know this person too well."
    when "banned"
      "All communication is blocked."
    end
  end
end

app/views/peers/_form.html.erb
<%= form_with(model: peer, class: "contents") do |form| %>
  <% if peer.errors.any? %>
    <div id="error_explanation" class="bg-rose-50 text-rose-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(peer.errors.count, "error") %> prohibited this peer from being saved:</h2>

      <ul>
        <% peer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :onion_address %>
    <%= form.text_field :onion_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="text-sm text-gray-400 ml-7 mt-2">
      Have your friend add you as a peer to access each others markets.
      <br />
      You address is <%= configatron.my_onion %>
    </p>
  </div>

  <div class="my-5">
    <%= form.label :trust_level, class: "mb-2" %>
    <div class="mt-5">
      <%= form.collection_radio_buttons :trust_level, peer_trust_levels, :first, :first, html_options: { class: 'mt-2' } do |b| %>
        <%= b.label do %>
          <div class="relative flex items-start">
            <div class="flex items-center h-5">
              <%= b.radio_button html_options: { class: "focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300" } %>
            </div>
            <div class="ml-3 text-sm">
              <label for="small" class="font-medium text-gray-700"><%= b.text.humanize %></label>
              <p id="small-description" class="text-gray-500"><%= peer_trust_level_description(b.text) %></p>
            </div>
          </div>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-700 text-white inline-block font-medium" %>
  </div>
<% end %>

app/views/peers/_peer.html.erb
<div id="<%= dom_id peer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= peer.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Onion address:</strong>
    <%= peer.onion_address %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this peer", peer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this peer', edit_peer_path(peer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/peers/_peers.html.erb
<%= detail_sidebar do %>
  <div class="DetailSidebar__item flex p-2 border-b sticky top-0">
    <%= link_to new_peer_path, class: "btn inline-flex items-center justify-center my-2 mx-4 rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:bg-blue-500 w-full" do %>
      <%= icon_plus %>
      <span>
        New peer
      </span>
    <% end %>
  </div>

  <% @peers.find_each do |peer| %>
    <%= link_to peer,class: "DetailSidebar__item block px-4 py-4 border-b #{selected_peer == peer ? 'DetailSidebar__item--selected' : ''}", data: { "turbo-frame": "detail_view" , action: "detail-sidebar#choose"} do %>
      <span class="flex items-center space-x-4 w-full">
        <span class="flex-1 flex space-x-2 w-full truncate">
      
          <span class="flex flex-col text-gray-500 text-sm text-ellipsis overflow-hidden">
            <span class="DetailSidebar__item__title flex items-center truncate font-bold text-gray-800">
              <%= peer_online_status(peer, type: :small) %>
              <%= peer.name %>
            </span>
            <span class="DetailSidebar__item__subtitle break-words text-gray-900 text-xs"><%= peer_onion_short(peer) %></span>
            <time class="DetailSidebar__item__timestamp text-xs" datetime="<%= peer.created_at.to_date %>">since <%= peer.created_at.to_date %></time>
          </span>
        </span>

        <div class="icon--trash" data-action="click->detail-sidebar#delete" data-detail-sidebar-endpoint-param="peers" data-detail-sidebar-record-id-param="<%= peer.id %>">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
          </svg>
        </div>
        
        <!-- Heroicon name: solid/chevron-right -->
        <div class='icon--chevron'>
          <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        </div>
      
      </span>
    <% end %>
  <% end %>
<% end %>

app/views/peers/edit.html.erb
<%= detail_sidebar_body do %>
  <div class="paper">
    <h1 class="paper__title">Editing peer</h1>

    <%= render "form", peer: @peer %>

    <%= button_to 'Delete', peer_path(@peer), method: :delete, data: { confirm: "Are you sure you want to delete this peer?" }, class: "button inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-white bg-rose-500 hover:bg-rose-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %> 
    <%= link_to "Show this peer", @peer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to peers", peers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/peers/new.html.erb
<div class="paper">
  <h1 class="paper__title">New peer</h1>

  <%= render "form", peer: @peer %>

  <%= link_to 'Back to peers', peers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/peers/show.html.erb
<%= render partial: 'peers', locals: { selected_peer: @peer } %>

<!-- This example requires Tailwind CSS v2.0+ -->
<%= detail_sidebar_body do %>
  <div class="md:flex md:items-center md:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
        <%= @peer.name %>
      </h2>
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <p class="break-words w-full">
          <%= @peer.onion_address %>
        </p>
      </div>
    </div>
    <div class="mt-4 flex md:mt-0 md:ml-4">
      <%= link_to 'Edit', edit_peer_path(@peer), class: "button inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>

      <button disabled type="button" class="ml-3 button inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" data-tooltip="Coming soon...">
        Message
      </button>
    </div>
  </div>

  <div class="flex mt-4">
    <%= peer_online_status(@peer) %>
    <span class="ml-2 text-gray-800 text-sm">
      <%= @peer.trust_level.humanize %>
    </span>    
  </div>


  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="mt-5">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Last 7 days
    </h3>
    <dl class="mt-5 grid grid-cols-1 rounded-lg bg-white shadow divide-y divide-gray-200 md:grid-cols-3 md:divide-y-0 md:divide-x">
      <div class="px-4 py-5 sm:p-6">
        <dt class="text-base font-normal text-gray-900">
          Total Ads
        </dt>
        <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
          <div class="flex items-baseline text-2xl font-semibold text-blue-600">
            <%= peer_ads_in(timeframe: 7.days.ago..Time.current) %>
            <span class="ml-2 text-sm font-medium text-gray-500">
              from <%= peer_ads_in(timeframe: 14.days.ago..7.days.ago) %>
            </span>
          </div>

          <div class="inline-flex items-baseline px-2.5 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800 md:mt-2 lg:mt-0">
            <!-- Heroicon name: solid/arrow-sm-up -->
            <svg class="-ml-1 mr-0.5 flex-shrink-0 self-center h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">
              Increased by
            </span>
            <%= peer_ads_in(timeframe: 7.days.ago..Time.current).to_f / ([peer_ads_in(timeframe: 14.days.ago..7.days.ago), 1].max) * 100 %>%
          </div>
        </dd>
      </div>

      <div class="px-4 py-5 sm:p-6 filter blur-sm">
        <dt class="text-base font-normal text-gray-900">
          Share rate
        </dt>
        <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
          <div class="flex items-baseline text-2xl font-semibold text-blue-600">
            58.16%
            <span class="ml-2 text-sm font-medium text-gray-500">
              from 56.14%
            </span>
          </div>

          <div class="inline-flex items-baseline px-2.5 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800 md:mt-2 lg:mt-0">
            <!-- Heroicon name: solid/arrow-sm-up -->
            <svg class="-ml-1 mr-0.5 flex-shrink-0 self-center h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">
              Increased by
            </span>
            2.02%
          </div>
        </dd>
      </div>

      <div class="px-4 py-5 sm:p-6 filter blur-sm">
        <dt class="text-base font-normal text-gray-900">
          Avg. Click Rate
        </dt>
        <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
          <div class="flex items-baseline text-2xl font-semibold text-blue-600">
            24.57%
            <span class="ml-2 text-sm font-medium text-gray-500">
              from 28.62%
            </span>
          </div>

          <div class="inline-flex items-baseline px-2.5 py-0.5 rounded-full text-sm font-medium bg-rose-100 text-rose-800 md:mt-2 lg:mt-0">
            <!-- Heroicon name: solid/arrow-sm-down -->
            <svg class="-ml-1 mr-0.5 flex-shrink-0 self-center h-5 w-5 text-rose-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">
              Decreased by
            </span>
            4.05%
          </div>
        </dd>
      </div>
    </dl>
  </div>

  <div class="flex mt-4">
    <span class="ml-2 text-gray-800 text-sm">
      <% if @peer.first_sync_at %>
        First sync <%= time_ago_in_words @peer.first_sync_at %> ago
      <% else %>
        Awaiting first sync
      <% end %>
    </span>
    
  </div>

<% end %>