config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/messages', to: 'message_threads#index', as: :message_threads
  post '/messages', to: 'message_threads#create'
  get '/messages/:uuid', to: 'message_threads#show', as: :message_thread
  post '/messages/:uuid/messages', to: 'messages#create', as: :message_thread_messages
  delete '/messages/:uuid', to: 'message_threads#destroy'

  get '/settings', to: 'settings#index'

  resources :ads do
    member do
      resources :message_threads, as: :ad_messages, only: [:new]
    end
  end
  resources :peers
  get '/marketplace', to: "marketplace#index"

  namespace :api do
    namespace :v1 do
      resources :ads, only: [:index, :create, :destroy]
      resources :messages, only: [:create]
      post 'webhook', to: 'webhook#create'
      get 'webhook/:uuid/:token', to: 'webhook#show'
      get 'status', to: 'status#show'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["WEB_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["WEB_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'peers#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peacekeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
  
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="lg:flex bg-gray-50">
    <nav class="sticky top-0 lg:relative z-20 flex lg:flex-col bg-rose-700 w-full h-18 lg:h-screen lg:w-28">
      <%= nav_link_to peers_path, "peers" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
        Peers
      <% end %>
      
      <%= nav_link_to marketplace_path, marketplace_nav_controller do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        Market
      <% end %>

      <%= nav_link_to ads_path, ads_nav_controller do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Ads
      <% end %>

      <%= nav_link_to messages_path, messages_nav_controller do %>
       <%= icon_chat %>
        Chat
      <% end %>

      <%= nav_link_to settings_path, "settings" do %>
        <%= icon_gear %>
        Settings
      <% end %>
    </nav>
    

    <main class="flex flex-col flex-col-reverse md:flex-row lg:w-screen lg:h-screen overflow-y-scroll relative bg-gray-50">
      <% if notice.present? %>
        <p 
          class="fixed right-1/3 left-1/3 z-20 text-center top-24 py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block"
          id="notice"
          data-controller="flash-notice"
          data-flash-notice-target="notice"
        >
          <%= notice %>
        </p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>